### ISSUE TITLE
pathfind_straight() always returns empty list on Python 3.7

### ISSUE THREAD

**Issue by PrivateCaller** [Tugcga/PyRecastDetour#4]
```pathfind_straight()``` always seems to return an empty list, even when using points received from ```get_navmesh_trianglulation()```

If it helps, the output of ```get_log()``` is:
```
Load mesh from obj: successfully done.
Building navigation:
 - 2280 x 1216 cells
 - 610.2K verts, 305.1K tris
delaunayHull: Removing dangling face 27 [15,8,-1].
delaunayHull: Removing dangling face 28 [15,8,-1].
Build Times
- Rasterize:    1516.61ms       (40.5%)
- Build Compact:        255.33ms        (6.8%)
- Filter Border:        877.04ms        (23.4%)
- Filter Walkable:      55.60ms (1.5%)
- Erode Area:   84.39ms (2.3%)
- Median Area:  0.00ms  (0.0%)
- Mark Box Area:        0.00ms  (0.0%)
- Mark Convex Area:     0.00ms  (0.0%)
- Mark Cylinder Area:   0.00ms  (0.0%)
- Build Distance Field: 122.46ms        (3.3%)
    - Distance: 90.10ms (2.4%)
    - Blur:     32.08ms (0.9%)
- Build Regions:        566.01ms        (15.1%)
    - Watershed:        410.95ms        (11.0%)
      - Expand: 209.49ms        (5.6%)
      - Find Basins:    14.24ms (0.4%)
    - Filter:   147.87ms        (3.9%)
- Build Layers: 0.00ms  (0.0%)
- Build Contours:       50.02ms (1.3%)
    - Trace:    35.99ms (1.0%)
    - Simplify: 3.88ms  (0.1%)
- Build Polymesh:       33.88ms (0.9%)
- Build Polymesh Detail:        121.26ms        (3.2%)
- Merge Polymeshes:     0.00ms  (0.0%)
- Merge Polymesh Details:       0.00ms  (0.0%)
=== TOTAL:      3749.34ms
>> Polymesh: 10054 vertices  5000 polygons
```

**Comment by Tugcga** [comment]
If you can, send me an *.obj file with input geometry. I will try to check, what it generate and where is a problem.

**Comment by PrivateCaller** [comment]
> If you can, send me an *.obj file with input geometry. I will try to check, what it generate and where is a problem.

[Pyramid.zip](https://github.com/Tugcga/PyRecastDetour/files/9387579/Pyramid.zip)

**Comment by Tugcga** [comment]
It looks like all works correct. Here is a screen with builded navmesh with default settings:

![navmesh_01](https://user-images.githubusercontent.com/38164660/185790485-44e50bf3-9665-4d44-abf1-c9f1f61d6a13.png)

When I call ```path = navmesh.pathfind_straight([-10.0, 0.6, -5.0], [40.0, 0.6, 12.0])``` then it returns ```[(-10.0, 0.6, -5.0), (5.7, 0.6, 8.8), (40.0, 0.6, 12.0)]```. This is a correct path.

But when you build navmesh with default parameters, then stars of the piramid is not walkable. To make navmesh more connected, increase ```agentMaxClimb``` parameter to ```1.4-1.5```. Then the builded navmesh will be the following:

![navmesh_02](https://user-images.githubusercontent.com/38164660/185790631-67632d5b-b572-4fff-a9d0-b4570eeeb33c.png)

And the following code

```
navmesh = rd.Navmesh()
navmesh.init_by_obj("Pyramid.obj")

settings = navmesh.get_settings()
settings["agentMaxClimb"] = 1.5
navmesh.set_settings(settings)

navmesh.build_navmesh()
path = navmesh.pathfind_straight([0.0, 1.4, 0.0], [77.0, 40.2, 0])
print(path)
```
outputs some long non-empty path.
